### ISSUE TITLE
Regex Engine

### ISSUE THREAD

**Issue by pkcwong** [pkcwong/tango-meteor#18]
- automatically crawl Time and Date from web page
- use moment.js for Datetime parser

**Comment by pkcwong** [comment]
If it is too difficult, you may hard-code settings such that it works perfectly for just some specific institutes.

**Comment by httpak** [comment]
I download moment.js, but I don't know how to use it.

**Comment by httpak** [comment]
Will do date regex tomorrow.

**Comment by httpak** [comment]
Done. Also add one for course code.
